### ISSUE TITLE
Participant JSON parsing

### ISSUE THREAD

**Issue by Poxleit** [Poxleit/FKevin#2]
The 'Participant' entity has the following attributes:
    - Name and Surname
    - Email
    - Phone number
    - Total Points

A JSON structure needs to be defined and the following functionality needs to be provided
    - Ability to add new participants to the JSON file
    - Ability to load participants from the JSON file
    - Ability to remove participants from the JSON file
    - Ability to sort JSON file based on participant points

**Comment by Jelena-Milev** [comment]
Do we need saveParticipants(LinkedList participants) method which would load list of participants into .json file?
